exports.data = [
    {
      name: "Somnath Rakshit ",
      photo: "https://drive.google.com/open?id=1ABDYe2c5_kNZpq5ZvMf_jsYAQhgn4Ufd",
      contact: "+1-737-333-1713",
      email: "somnath52@gmail.com",
      institution: "Jalpaiguri Government Engineering College",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "Walmart Global Tech",
      position: "Senior Data Scientist",
      area: "Data Science",
      link: "https://www.linkedin.com/in/somnathrakshit",
      message: "Thank you sir, for your patience in teaching us not only computer science but also the value of perseverance, hard work, and integrity. I have learnt a lot from you and will cherish your teachings for many years to come. "
    },
    {
      name: "Ritabrata Ghosh",
      photo: "https://drive.google.com/open?id=1c1G2KCCx83PBeTriGGZHWt56vVrtJ2vy",
      contact: 8100137310,
      email: "ritabrata.ghosh95@gmail.com",
      institution: "Jalpaiguri Govt Engineering College",
      meet: 2014,
      degree: "B. Tech",
      dept: "CSE",
      org: "IBM India Pvt Ltd",
      position: "Senior Test Analyst",
      area: "Test Automation"
    },
    {
      name: "Arpit Sanghai",
      photo: "https://drive.google.com/open?id=1HcNDLFMxWQm77gfVZVNHMFrUMJpzRZP9",
      contact: 7384700684,
      email: "arpitsanghai.id@gmail.com",
      institution: "Jalpaiguri Government Engineering College ",
      meet: "2nd year",
      degree: "B. Tech",
      dept: "CSE",
      org: "IIT BHU",
      position: "Mtech student",
      area: "Eeg signals processing ",
      link: "https://www.linkedin.com/in/arpit-sanghai-iit-bhu?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      message: "Really lucky to come across a person like you. I have heard about Gurus in ancient texts how they not only taught skills to their students but also life lessons. You are not a teacher ,a professor, rather a Guru who motivated me whenever I felt low and when the world was against me you were only one of the few persons who believed in my abilities. Thank you for always being there sir"
    },
    {
      name: "Sabyasachi Samadder ",
      photo: "https://drive.google.com/open?id=1b5aSOD2JMrswHnncVVdGcsgLKjPffzfg",
      contact: 8481058739,
      email: "sachi.samadder@gmail.com",
      institution: "Jalpaiguri Government Engineering College ",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "Tutorialspoint ",
      position: "Technical Content Manager ",
      area: "Hyderabad",
      link: "https://www.linkedin.com/in/%0Asabyasachi-samadder-103850143/",
      message: "Thank you sir for this initiative."
    },
    {
      name: "Sushmita Sarkar ",
      photo: "https://drive.google.com/open?id=1Q19-Qs2lbFfXAryURr6vRSkBFpzSbWrg",
      contact: 7029224436,
      email: "sarkarsushmita26@gmail.com",
      institution: "Jalpaiguri government engineering college ",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "JP Morgan & chase",
      position: "SWE2",
      area: "Full stack developer",
      link: "http://linkedin.com/in/sushmita-sarkar-51b1a7138",
      message: "It was great experience and I was able to learn a lot and made me compatible in industry level"
    },
    {
      name: "Snehasish Das",
      photo: "https://drive.google.com/open?id=1mcb4fMgNSYz8ZdIcQhbEYS_yVpRxT8g0",
      contact: 8981497361,
      email: "snehasish.das.work@gmail.com",
      institution: "Jalpaiguri Government Engineering College",
      meet: 2014,
      degree: "B. Tech",
      dept: "CSE",
      org: "Nutanix",
      position: "Member of Technical Staff - 3",
      area: "Software Developer",
      link: "https://www.linkedin.com/in/snehasish-das-9988581a9?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      message: "Your impact on my personal and academic growth since joining college has been profound. Your guidance, encouragement, and support have played a crucial role in my productivity and self-improvement. Your dedication to students sets an unmatched example, inspiring me to be equally committed to my responsibilities. I distinctly remember the calls you gave me when I missed important lectures or seminars due to oversleeping. Those have acted as wake-up calls for me and pushed me to take my studies and career more seriously. Thank you for being such an amazing professor."
    },
    {
      name: "Soumitra Saha",
      photo: "https://drive.google.com/open?id=1CFb3r6cLbPJl5mO3Sbr0SGEn4-n4cLOc",
      contact: 9832416547,
      email: "soumitrasaha12@gmail.com",
      institution: "JGEC",
      meet: 2014,
      degree: "B. Tech",
      dept: "CSE",
      org: "IBM ",
      position: "Senior Developer ",
      area: ".Net, API, SQL"
    },
    {
      name: "SAURAV NANDI",
      photo: "https://drive.google.com/open?id=1uNx5PEb0vpk5Zsg4OSIY_vAz5hFlTpGE",
      contact: 6290232044,
      email: "Sourav108live@gmail.com",
      institution: "JALPAIGURI GOVERNMENT ENGINEERING COLLEGE",
      meet: 2014,
      degree: "B. Tech",
      dept: "Computer Science & Engineering",
      org: "Central Public Works Department",
      position: "Auditor",
      area: "3rd floor, Cgo complex, salt lake, sector-1, kolkata-64 ",
      message: "I am thankful to you for your guidance and i became more mature and focused in my career and life. I have enjoyed a great college life in your tenure as HOD of CSE department. You have already made the department the strongest. Moreover, I will be the \"The Chanakya\" of your team forever...."
    },
    {
      name: "ATUL KUMAR",
      photo: "https://drive.google.com/open?id=1m_kCh7WhpIfhwrb7SGf4htQ-B_LE4ICv",
      contact: 7908153700,
      email: "atul070kumar@gmail.com",
      institution: "JGEC",
      meet: 2017,
      degree: "B. Tech",
      dept: "ECE",
      org: "IT",
      position: "CONSULTANT",
      area: "SOFTWARE",
      link: "https://www.linkedin.com/in/atul-k-262405a6/",
      message: "Best time i could remember is in the year 2020. Collaborated with you and organised n number of events in colleges where got to know about you. I remember Seminar on trekking, COMSYS and Kedarkantha trek"
    },
    {
      name: "Anmol Binani",
      photo: "https://drive.google.com/open?id=1k1HQo8MzqTFKG22-6ActOMiiwNNSBY2O",
      contact: 9832528162,
      email: "anmolbinani@gmail.com",
      institution: "JGEC",
      meet: 2014,
      degree: "B. Tech",
      dept: "CSE",
      org: "SAP Labs",
      position: "Developer",
      area: "Back End",
      link: "https://www.linkedin.com/in/anmol-binani/",
      message: "Have spent so much time with you in your office discussing various topics be it course or life related. It was such good days :)\nIt was you because of whom I was able to get an internship with great people who taught me so much and it holds relevant even today and that learning I pass on to my juniors or teammates."
    },
    {
      name: "Samanwita Das",
      photo: "https://drive.google.com/open?id=1C5oL07KQHqEQppcDFZaXoJeCNm7ABnt1",
      contact: "7980376635 /+1 940 326 2226",
      email: "samanwita.das99@gmail.com",
      institution: "Jalpaiguri Government Engineering College ",
      meet: 2019,
      degree: "B. Tech",
      dept: "IT",
      org: "Not working currently. IBM previously ",
      position: "NA",
      area: "NA",
      message: "The way you took our classes was my best college life memory, your classes were so interesting and you inspired us a lot not only studies but also the way of our life long journey."
    },
    {
      name: "Soham Sen",
      photo: "https://drive.google.com/open?id=1Z56VWAfy5jhcSsQ23quCHBcExfvOa72f",
      contact: 7439710150,
      email: "aoham2014sen@gmail.com",
      institution: "Jalpaiguri Government Engineering College",
      meet: 2022,
      degree: "B. Tech",
      dept: "EE",
      org: "Erasmus Mundus Joint Masters in Game Design",
      position: "Masters Student",
      area: "Research",
      link: "www.linkedIn.com/nuclearcactus",
      message: "Thank you sir for the constant guidance, support and lessons you have taught me. I have become more confident and capable under your supervision. In my early years of college, I was extremely disheartened as I didn't get to study computer science. You gave me the push when I was at my lowest to do research and venture outside the curriculum, and it has rewarded me handsomely. As my graduation draws near, I am proud to say that I had a teacher like you, and I stand where I am today because of you. Thank you sir, for everything."
    },
    {
      name: "Sampriti Ganguly",
      photo: "https://drive.google.com/open?id=1GPIO1PapYiSOxcvFXUa2ahfSRKZEu5sp",
      contact: 8670508132,
      email: "sampritig2023@email.iimcal.ac.in",
      institution: "Jalpaiguri Government Engineering College",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "Accenture Strategy & Consulting",
      position: "Management Consulting Analyst",
      area: "Business Consulting, Supply Chain & Operations",
      link: "https://www.linkedin.com/in/sampriti-ganguly-9b8145213/",
      message: "Thank you Sir for this fantastic initiative! I'm genuinely eager to lend a hand to anyone within this network who's seeking personal or professional development and, at the same time excited about the opportunity to collaborate and glean insights from fellow members."
    },
    {
      name: "Anuran Pandit",
      photo: "https://drive.google.com/open?id=1NbsGgho2bueBrqknznQdlqBWaDylKmgM",
      contact: 8653833393,
      email: "anuranpandit95@gmail.com",
      institution: "Jalpaiguri Government Engineering College ",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "Capgemini ",
      position: "Consultant ",
      area: "Development and maintenance of client facing software ",
      message: "Sir, thank you for joining JGEC when you did. We would have ended up nowhere if it wasn't for you. "
    },
    {
      name: "Riyanka Kundu ",
      photo: "https://drive.google.com/open?id=1Gs3Y_-c7_5ie2g3d72Guwp6s9zkwKIG1",
      contact: 8927374112,
      email: "riyankakundu@gmail.com",
      institution: "JGEC",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "CITI",
      position: "Officer C11",
      area: "Web Developer ",
      link: "https://www.linkedin.com/in/riyanka-kundu-96bb7b139",
      message: "Huge bunch of memories of learning and working under DKK sir. Feeling nostalgic to be a part of this group."
    },
    {
      name: "Sekh Abdul Aziz",
      photo: "https://drive.google.com/open?id=1fkOSmbFxxgAQrnQYAVv7Z_TRbcP6AxsW",
      contact: 8972740075,
      email: "abdulaziz2020.aa@gmail.com",
      institution: "Jalpaiguri Government Engineering College",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "Deloitte Consulting ",
      position: "Consultant ",
      area: "Consulting "
    },
    {
      name: "Bhaskar Konar",
      photo: "https://drive.google.com/open?id=1kACTkkWOOPMRS_7_stWpP5eBI_8birXH",
      contact: "+447405675239",
      email: "konar.bhaskar@gmail.com",
      institution: "MCKV",
      meet: 2001,
      degree: "BE",
      dept: "CSE",
      org: "Own Consulting Firm",
      position: "Director",
      area: "Data & Analytics",
      message: "Sir, Is an inspiration for student like me."
    },
    {
      name: "Gargi Mitra",
      photo: "https://drive.google.com/open?id=1PWbbcyhrcF5iUp7A5TLx4rvyRPeW-MiP",
      contact: "+1 672 558 4468",
      email: "gargimiitm@gmail.com",
      institution: "St. Thomas' College of Engineering & Technology",
      meet: 2010,
      degree: "B. Tech",
      dept: "CSE",
      org: "University of British Columbia (Vancouver)",
      position: "Postdoctoral Research Fellow",
      area: "Cyber security",
      link: "https://www.linkedin.com/in/gargimitraiitm/",
      message: "Prof. Dipak Kumar Kole (DKK Sir, as we call him) is the person who introduced me to the concept of \"research\". He has played a pivotal role in helping me find my passion, shaping my career, and guided me at every step (even after my STCET days), going above and beyond his official responsibilities as a teacher. I consider myself to be extremely fortunate to have crossed paths with you, Sir."
    },
    {
      name: "Priti Gupta ",
      photo: "https://drive.google.com/open?id=14eL1nIqZ9gHHl8bKpnWgmOQTpFPaJPQY",
      contact: "8906817338/8240178920",
      email: "pritigupta220596@gmail.com",
      institution: "Jalpaiguri Government Engineering College ",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "Bank of Newyork Mellon ",
      position: "Senior Quantity Engineer ",
      area: "SDET",
      link: "https://www.linkedin.com/in/priti-gupta-ab70a4144?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
      message: "First of all I will take this opportunity to say 'Thank You' for giving me all your mentorship and opportunities, which enables me to explore my career in every directions throughout my college life. The unforgettable memories which I have is our 10 days IIT Mandi trip, which was the package of learning, traveling, exploring and lots of fun together."
    },
    {
      name: "Rounak De",
      photo: "https://drive.google.com/open?id=1Rv_ub9jkN5uMZC9FGXHLu9D0YCofR_I_",
      contact: "+1 8602098925",
      email: "derounak1721@gmail.com",
      institution: "JGEC",
      meet: 2017,
      degree: "B. Tech",
      dept: "CSE",
      org: "SAP America",
      position: "Technology Consultant",
      area: "Tech Consulting in SAP",
      link: "https://www.linkedin.com/in/rounak-de/"
    },
    {
      name: "Priyajit Ghosh",
      photo: "https://drive.google.com/open?id=1j7P2AqWUkjEHb9Z7BjSHJqyj9LoWEhIN",
      contact: "+491783205780",
      email: "priyajitghosh1@gmail.com",
      institution: "Jalpaiguri Government Engineering College",
      meet: 2014,
      degree: "B. Tech",
      dept: "CSE",
      org: "Accenture GmbH",
      position: "Packaged Application Development Specialist",
      area: "Salesforce",
      link: "https://www.linkedin.com/in/priyajit-ghosh-285a26102",
      message: "The reason why the department began to be considered across the college and the state is you and your vision. That being said thank you for guiding us through the three years you taught us."
    },
    {
      name: "Dev Khaitan",
      photo: "https://drive.google.com/open?id=1vU1VQ2_pWzCZZPLa4vdJbqrqpZpU6gCY",
      contact: 7602026306,
      email: "devkhaitan7 @gmail.com",
      institution: "Jalpaiguri Govt Engineering College",
      meet: 2016,
      degree: "B. Tech",
      dept: "CSE",
      org: "Infosys pvt ltd",
      position: "Senior System Engineer",
      area: "Sap,Bigdata"
    },
    {
      name: "Subhrasankar Chatterjee",
      photo: "https://drive.google.com/open?id=1azriVDffkd7rC4_y7zZGjhdt3UgQpCnc",
      contact: 9733143881,
      email: "subhrasankar.chatterjee000@gmail.com",
      institution: "Jalpaiguri Government Engineering College ",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "IIT Kharagpur ",
      position: "Doctoral Researcher ",
      area: "Computational Neuroscience "
    },
    {
      name: "SARBBESWAR DEY",
      photo: "https://drive.google.com/open?id=1cmUFZVrlDtW8P4OwTimkf7waj9dFEVKV",
      contact: 9531767083,
      email: "deysarbbeswar@gmail.com",
      institution: "Jalpaiguri government engineering college",
      meet: 2015,
      degree: "B. Tech",
      dept: "CSE",
      org: "DXC Technology",
      position: "Analyst I Software Engineering",
      area: "Production support"
    }
  ];